CREATE TABLE "offer" (
	"offer_id" varchar(64), 
	"active" bool,
	"single_use" bool,
	"bolt12" text,
	"bolt12_unsigned" text,
	"used" bool,
	"label" varchar(255),
	"created" bool,
	"amount" varchar(255),
	"quoted_currency" varchar(255),
	"quoted_amount" varchar(255),
	"description" varchar(255),
	"vendor" varchar(255),
	"quantity_min" int,
	"quantity_max" int,
	"absolute_expiry" int,
	"recurrence" varchar(255),
	"recurrence_base" varchar(255),
	"recurrence_paywindow" varchar(255),
	"recurrence_limit" int,
	"refund_for" varchar(255),
	"metadata" text,
	"created_at" integer NOT NULL,
	PRIMARY KEY (offer_id)
);